config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  # Define a route for standard pages
  get 'pages/:title', to: 'pages#show', as: :page

  # Define a route for nested pages
  get 'pages/:category/:title', to: 'pages#show_nested', as: :nested_page


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post '/api/exchange_token', to: 'authentication#exchange_token'

  get '/api/redirect_to_discord', to: 'authentication#redirect_to_discord'
  get '/api/discord/callback', to: 'authentication#discord_callback'
  get '/api/discord/start_auth', to: 'authentication#start_auth'

  get '/map', to: 'maps#index'

  resources :regions
  resources :wall_comments, only: [:create, :destroy]
  resources :discords
  resources :photos do
    resources :photo_comments do 
      post 'upvote'
      post 'downvote'
    end
    member do
      post 'view'
      post 'upvote'
      post 'downvote'
    end
  end
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  resources :votes, only: [:create]
  get '/dashboard', to: 'home#dashboard'
  get '/gallery', to: 'home#gallery'
  resources :messages
  # Events
 # get '/events/new', to: 'events#new', as: 'new_event'
 # get '/events', to: 'events#index', as: 'find_event'
 # post '/events', to: 'events#create'

 #post '/admin/events/:id/publish', to: 'admin#publish_event', as: 'publish_event'
 #post '/admin/events/:id/trash', to: 'admin#trash_event', as: 'trash_event'

 namespace :api do
  resources :regions, only: [:index], defaults: { format: :json }
  resources :events, only: [:index], defaults: { format: :json }
  # other API routes...
end

  namespace :admin do
    root to: 'dashboard#index'  # Example admin dashboard
    get '/calendar', to: 'calendar#index'
    get '/profile', to: 'users#show'
    resources :events do
      collection do
        get 'all', to: 'events#all'  # Adding this line
      end
      member do
        post 'publish'
        post 'trash'
      end
    end

    resources :regions do
      member do
        post 'publish'
        post 'trash'
      end
    end
    resources :sections, only: [:create, :destroy, :update]
    resources :blocks, only: [:create, :destroy, :update]
    resources :settings 
    resources :pages
    resources :posts do
      member do
        post 'trash'
      end
    end

    resources :replies do
      member do
        post 'trash'
      end
    end

    resources :messages do
      member do
        post 'trash'
      end
    end

    resources :badges do
      member do
        post 'trash'
      end
    end

    resources :user_badges do
      member do
        post 'trash'
      end
    end
    
    resources :discords do
      member do
        post 'publish'
        post 'unpublish'
        post 'trash'
      end
    end

    resources :users do
      member do
        post 'publish'
        post 'unpublish'
        post 'trash'
        patch :update_user_level, to: 'users#update_user_level'
      end
    end

    resources :photos do
      member do
        post 'publish'
        post 'unpublish'
        post 'trash'
      end
    end
  # ... other admin resources ...
  end

  resources :users, only: [:show, :edit, :update, :destroy]
  get 'new_category', to: 'post_categories#new'
  get 'virtual-events', to: 'events#virtual'
  get 'virtual-events/:slug', to: 'events#show_virtual', as: 'virtual_event'

  resources :events do
    resources :event_participations, only: [:create, :destroy]
    resources :photos, only: [:new, :create, :show, :destroy]
    resources :event_managers
    resources :giveaways do
      member do
        post 'draw_winner'
      end
    end
    member do
      post 'join'
      delete 'leave'
    end
  end

  get '/forum', to: 'forum#index'
  namespace :forum do
    get 'new_category', to: 'post_categories#new'
    resources :post_categories do
      resources :posts do
        resources :replies, only: [:new, :create, :show]
      end
    end
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'  
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/invite', to: 'events#invite', as: 'invite'


  # Defines the root path route ("/")
   root "home#index"
   get '/:id', to: 'regions#show', as: :region_shortcut
end

app/views/admin/pages/_form.html.erb
<!-- Form Container -->
<div class="flex-grow">
  <%= form_with model: Page.new, url: admin_pages_path, local: true, class: "flex flex-col px-2 space-y-4" do |form| %>
    <div class="mb-4">
    <%= form.label :title, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :title, required:true, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    <% if @page.errors.full_messages_for(:name).any? %>
      <p class="text-red-500 text-xs italic"><%= @page.errors.full_messages_for(:name).join(', ') %></p>
    <% end %>
  </div>

  <!-- Category Field -->
  <div class="mb-4">
    <%= form.label :category, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :category, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    <% if @page.errors.full_messages_for(:category).any? %>
      <p class="text-red-500 text-xs italic"><%= @page.errors.full_messages_for(:category).join(', ') %></p>
    <% end %>
  </div>

  <!-- Slug Field -->
  <div class="mb-4">
    <%= form.label :slug, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :slug, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    <% if @page.errors.full_messages_for(:slug).any? %>
      <p class="text-red-500 text-xs italic"><%= @page.errors.full_messages_for(:slug).join(', ') %></p>
    <% end %>
  </div>


  <div class="mb-4">
  <%= form.label :banner, 'Banner', class: 'text-gray-900 dark:text-white' %>
      <%= form.file_field :banner, class:'shadow border rounded py-2 px-3 text-gray-700 dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700' %>
      <% if @page.errors.full_messages_for(:banner).any? %>
      <p class="text-red-500 text-xs italic"><%= @page.errors.full_messages_for(:banner).join(', ') %></p>
    <% end %>
  </div>


    <!-- Submit Button -->
    <div>
    <%= form.submit "Create Page", class: "p-2 rounded-lg bg-blue-500 hover:bg-blue-700 text-white" %>
    </div>
<% end %>
</div>

app/views/admin/pages/_page.html.erb

<div class="grid grid-cols-3 border-b border-stroke dark:border-strokedark sm:grid-cols-6">
<div class="flex items-center gap-3 p-2.5 xl:p-5">
  <div class="flex-shrink-1">
    <img src="<%= page.user.profile_image %>" alt="User" />
  </div>
  <p class="hidden font-medium  dark:text-white sm:block">
    <%= page.user.username %>
  </p>
</div>

<div class="flex items-center justify-center p-2.5 xl:p-5" style="max-width:100px; overflow-x:scroll">
  <p class="font-medium  dark:text-white"><%= page.title %></p>
</div>
<div class="flex items-center justify-center p-2.5 xl:p-5">
  <p class="font-medium  dark:text-white"><%= page.category %></p>
</div>

<div class="hidden items-center justify-center p-2.5 sm:flex xl:p-5">
  <p class="font-medium text-meta-5 text-white"> <%= page.description %></p>
</div>

<div class="hidden items-center justify-center p-2.5 sm:flex xl:p-5">
  <p class="font-medium dark:text-white"><%= page.created_at.strftime('%a %b %d, %Y %l:%M %p') %></p>
</div>

<div class="hidden items-center justify-center p-2.5 sm:flex xl:p-5">
<p class="font-medium text-meta-5 text-white">
<%= link_to 'Edit', edit_admin_page_path(page), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>

</p>
</div>
</div>

app/views/admin/pages/edit.html.erb
<div class="container mx-auto px-4 dark:bg-gray-800">
  <h1 class="text-xl font-bold my-4 text-gray-900 dark:text-white">Edit Page</h1>
  
  <!-- Form for editing the pageable attributes -->
  <% comment do %>
  <%= form_with model: @page, url: admin_page_path(@page), local: true do |form| %>

    <!-- Add fields specific to the pageable type -->
    <!-- Example for a VideoPage -->
    <% if @page.pageable_type == "VideoPage" %>
      <%= form.label :title %>
      <%= form.text_field :title %>
      <!-- Other fields specific to VideoPage -->
    <% end %>
    <!-- Add similar conditional blocks for other pageable types -->

    <%= form.submit 'Update Page', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
  <% end %>


  <% end %>




  <%= form_with model: @page, url: admin_page_path(@page), local: true do |form| %>

<!-- Title Field -->
    <div class="mb-4">
    <%= form.label :title, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :title, required:true, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    <% if @page.errors.full_messages_for(:name).any? %>
      <p class="text-red-500 text-xs italic"><%= @page.errors.full_messages_for(:name).join(', ') %></p>
    <% end %>
  </div>

  <!-- Category Field -->
  <div class="mb-4">
    <%= form.label :category, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :category, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    <% if @page.errors.full_messages_for(:category).any? %>
      <p class="text-red-500 text-xs italic"><%= @page.errors.full_messages_for(:category).join(', ') %></p>
    <% end %>
  </div>

  <!-- Title Field -->
  <div class="mb-4">
  <%= form.label :description, class: "block text-gray-700 text-sm font-bold mb-2" %>
  <%= form.text_area :description, required:true, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  <% if @page.errors.full_messages_for(:name).any? %>
    <p class="text-red-500 text-xs italic"><%= @page.errors.full_messages_for(:name).join(', ') %></p>
  <% end %>
</div>

  <!-- Slug Field -->
  <div class="mb-4">
    <%= form.label :slug, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :slug, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    <% if @page.errors.full_messages_for(:slug).any? %>
      <p class="text-red-500 text-xs italic"><%= @page.errors.full_messages_for(:slug).join(', ') %></p>
    <% end %>
  </div>



  <div class="mb-4">
  <%= form.label :banner, 'Banner', class: 'text-gray-900 dark:text-white' %>
      <%= form.file_field :banner, class:'shadow border rounded py-2 px-3 text-gray-700 dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700' %>
      <% if @page.errors.full_messages_for(:banner).any? %>
      <p class="text-red-500 text-xs italic"><%= @page.errors.full_messages_for(:banner).join(', ') %></p>
    <% end %>
  </div>

  
  <%= form.submit 'Update Page', class: "bg-citizen-blue-highlight text-white font-bold py-2 px-4 rounded" %>


<% end %>

  <!-- Forms for editing blocks in each section -->
  <% @page.sections.each do |section| %>
    <% section.blocks.each do |block| %>
      <%= form_with model: [:admin, block], local: true do |form| %>
        <%= form.label :title %>
        <%= form.text_field :title %>
  
        <%= form.label :description %>
        <%= form.text_area :description %>
  
        <div>
          <%= form.label :image %>
          <%= form.file_field :image, class: 'w-full bg-gray-700 text-white' %>
        </div>
  
        <h2 class="text-lg font-bold mt-4 mb-2">Translations</h2>
        <%= form.fields_for :translations, block.translations do |translation_form| %>
          <div class="border p-4 rounded mb-2">
            <%= translation_form.label :language %>
            <%= translation_form.text_field :language %>
        
            <%= translation_form.label :title %>
            <%= translation_form.text_field :title %>
        
            <%= translation_form.label :description %>
            <%= translation_form.text_area :description %>
          </div>
        <% end %>
  
        <%= form.submit 'Update Block', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
      <% end %>
      <%= button_to 'Delete Block', admin_block_path(block), method: :delete, data: { confirm: 'Are you sure?' }, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
    <% end %>
  <% end %>
  
  <!-- Back Button -->
  <%= link_to 'Back to Settings', admin_settings_path, class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded" %>
</div>

app/views/admin/pages/index.html.erb
<div class="rounded-sm border border-gray-300 shadow-md dark:border-gray-700 dark:bg-gray-800">
    <div class="py-6 px-4 md:px-6 xl:px-7.5">
      <h4 class="text-xl font-bold text-gray-900 dark:text-white">Pages</h4>
    </div>
  

    <%= render 'form' %>

    <div class="grid grid-cols-3 rounded-sm bg-gray-900 dark:bg-gray-900 sm:grid-cols-6">
      <div class="p-2.5 xl:p-5">
        <h5 class="text-sm font-medium uppercase xsm:text-base text-gray-900 dark:text-white">Author</h5>
      </div>
      <div class="p-2.5 text-center xl:p-5">
        <h5 class="text-sm font-medium uppercase xsm:text-base text-gray-900 dark:text-white">Title</h5>
      </div>
      <div class="p-2.5 text-center xl:p-5">
        <h5 class="text-sm font-medium uppercase xsm:text-base text-gray-900 dark:text-white">Category</h5>
      </div>
      <div class="p-2.5 text-center xl:p-5">
        <h5 class="text-sm font-medium uppercase xsm:text-base text-gray-900 dark:text-white">Description</h5>
      </div>
      <div class="hidden p-2.5 text-center sm:block xl:p-5">
        <h5 class="text-sm font-medium uppercase xsm:text-base text-gray-900 dark:text-white">Created</h5>
      </div>
      <div class="hidden p-2.5 text-center sm:block xl:p-5">
      <h5 class="text-sm font-medium uppercase xsm:text-base text-gray-900 dark:text-white">Action</h5>
    </div>
    </div>
  
    <% if @pages.count > 0 %>
      <% @pages.each do |page| %>
        <%= render 'page', page: page %>
      <% end %>
    <% else %>
      <div class="text-center py-4">
        <p class="text-gray-500 dark:text-gray-400">No pages found.</p>
      </div>
    <% end %>
  
  </div>
  