config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  # Define a route for standard pages
  get 'pages/:title', to: 'pages#show', as: :page

  # Define a route for nested pages
  get 'pages/:category/:title', to: 'pages#show_nested', as: :nested_page


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post '/api/exchange_token', to: 'authentication#exchange_token'

  get '/api/redirect_to_discord', to: 'authentication#redirect_to_discord'
  get '/api/discord/callback', to: 'authentication#discord_callback'
  get '/api/discord/start_auth', to: 'authentication#start_auth'

  get '/map', to: 'maps#index'

  resources :regions
  resources :wall_comments, only: [:create, :destroy]
  resources :discords
  resources :photos do
    resources :photo_comments do 
      post 'upvote'
      post 'downvote'
    end
    member do
      post 'view'
      post 'upvote'
      post 'downvote'
    end
  end
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  resources :votes, only: [:create]
  get '/dashboard', to: 'home#dashboard'
  get '/gallery', to: 'home#gallery'
  resources :messages
  # Events
 # get '/events/new', to: 'events#new', as: 'new_event'
 # get '/events', to: 'events#index', as: 'find_event'
 # post '/events', to: 'events#create'

 #post '/admin/events/:id/publish', to: 'admin#publish_event', as: 'publish_event'
 #post '/admin/events/:id/trash', to: 'admin#trash_event', as: 'trash_event'

 namespace :api do
  resources :regions, only: [:index], defaults: { format: :json }
  resources :events, only: [:index], defaults: { format: :json }
  # other API routes...
end

  namespace :admin do
    root to: 'dashboard#index'  # Example admin dashboard
    get '/calendar', to: 'calendar#index'
    get '/profile', to: 'users#show'
    resources :events do
      collection do
        get 'all', to: 'events#all'  # Adding this line
      end
      member do
        post 'publish'
        post 'trash'
      end
    end

    resources :regions do
      member do
        post 'publish'
        post 'trash'
      end
    end
    resources :sections, only: [:create, :destroy, :update]
    resources :blocks, only: [:create, :destroy, :update]
    resources :settings 
    resources :pages
    resources :posts do
      member do
        post 'trash'
      end
    end

    resources :replies do
      member do
        post 'trash'
      end
    end

    resources :messages do
      member do
        post 'trash'
      end
    end

    resources :badges do
      member do
        post 'trash'
      end
    end

    resources :user_badges do
      member do
        post 'trash'
      end
    end
    
    resources :discords do
      member do
        post 'publish'
        post 'unpublish'
        post 'trash'
      end
    end

    resources :users do
      member do
        post 'publish'
        post 'unpublish'
        post 'trash'
        patch :update_user_level, to: 'users#update_user_level'
      end
    end

    resources :photos do
      member do
        post 'publish'
        post 'unpublish'
        post 'trash'
      end
    end
  # ... other admin resources ...
  end

  resources :users, only: [:show, :edit, :update, :destroy]
  get 'new_category', to: 'post_categories#new'
  get 'virtual-events', to: 'events#virtual'
  get 'virtual-events/:slug', to: 'events#show_virtual', as: 'virtual_event'

  resources :events do
    resources :event_participations, only: [:create, :destroy]
    resources :photos, only: [:new, :create, :show, :destroy]
    resources :event_managers
    resources :giveaways do
      member do
        post 'draw_winner'
      end
    end
    member do
      post 'join'
      delete 'leave'
    end
  end

  get '/forum', to: 'forum#index'
  namespace :forum do
    get 'new_category', to: 'post_categories#new'
    resources :post_categories do
      resources :posts do
        resources :replies, only: [:new, :create, :show]
      end
    end
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'  
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/invite', to: 'events#invite', as: 'invite'


  # Defines the root path route ("/")
   root "home#index"
   get '/:id', to: 'regions#show', as: :region_shortcut
end

app/views/shared/_base_radio.html.erb
<nav class="navbar-wrapper navbar-bottom-fixed base-shadow">
    <div class="navbar navbar-expand player-header bd-navbar">
        
        <div class="d-flex align-items-center">
            <a href="#" data-toggle="push-menu" class="paper-nav-toggle pp-nav-toggle  paper-nav-toggle-sidenav ml-2 mr-2">
                <i></i>
            </a>
            <a class="navbar-brand d-none d-lg-block" href="/">
                <div class="d-flex align-items-center s-14 l-s-2 base-orange">
                    <span>THE BASE</span>
                </div>
            </a>
        </div>
        
        <div class="d-flex align-items-center d-none d-lg-flex ml-2 mr-2">
            <a class="btn btn-link d-none d-lg-block" href="/webplayer">
                <div class="display-currentart"></div>
            </a>
            
            <a class="btn btn-link d-none d-lg-block" href="/webplayer">
                <span id="display-currentsong-tracker" class="display-currentsong"></span><br>
                <small class="display-currentalbum"></small>
            </a>
        
        </div>
        
        <div class="player-bar mr-auto" id="mediaPlayer" data-auto="false">
            <div class="row align-items-center grid">
                <div class="col">

                    <button class="btn btn-link" id="playPause">
                        <span id="play"><i class="icon-play s-36 text-primary"></i></span>
                        <span id="pause" style="display: none"><i class="icon-pause s-36 text-primary"></i></span>
                    </button>

                    <div id="waveform" style="display:none"></div>
                
                    <a class=" btn btn-link pls-dl" href="https://social.thebase.sc/thebase.pls" target="_blank" download>
                        <i class="icon-download"></i>
                    </a>
                
                    <a class="btn" data-toggle="control-sidebar">
                        <i class="fal fa-comments-alt"></i>
                    </a>
                    
                </div>
            </div>
        </div>
        
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="searchOverlay-wrap">
                    <a href="#" id="btn-searchOverlay" class="nav-link mr-3 btn--searchOverlay no-ajaxy">
                        <i class="icon icon-search s-24"></i>
                    </a>
                </li>
            </ul>
        </div>
        
    </div>
</nav>

app/views/shared/_footer.html.erb


<footer class="bg-gray-800 text-white mt-8 p-4">
  <div class="text-center p-4">
    <p>If you can't find answers in our Frequently Asked Questions section, feel free to email us at info@barcitizen.org with details. We usually respond within 24 hours!</p>
  </div>
  
  <!-- Footer Blocks Container -->
  <div class="flex flex-col md:flex-row justify-between items-center md:items-start">
    
    <!-- Quick Links Block -->
    <div class="flex-1 p-2">
      <h5 class="font-bold"><%= t 'footer.quicklinks' %></h5>
      <ul class="mt-2">
        <li>About</li>
        <li>FAQs</li>
        <li>Privacy Policy</li>
        <li>Refund Policy</li>
        <!-- More links here -->
      </ul>
    </div>
    
    <!-- Contact Us Block -->
    <div class="flex-1 p-2">
      <h5 class="font-bold"><%= t 'footer.contact_us' %></h5>
      <p class="mt-2">Email: info@barcitizen.org</p>
      <p>Phone: (866) 483-2695</p>
      <!-- More contact details here -->
    </div>
    
    <!-- Connect With Us Block -->
    <div class="flex-1 p-2">
      <h5 class="font-bold"><%= t 'footer.connect_with_us' %></h5>
      <div class="social-links flex mt-2">
      
      <!-- Instagram Button -->
      <a href="https://www.instagram.com" class="bg-white p-2 mx-1 items-center justify-center rounded-full hover:bg-gray-300">
     
          <%= render '/shared/icons/instagram' %>
      </a>
      
      <!-- Twitter Button -->
      <a href="https://www.twitter.com" class="bg-white p-2  mx-1  items-center justify-center rounded-full hover:bg-gray-300">
      <%= render '/shared/icons/x' %>
      </a>
      
      <!-- Facebook Button -->
      <a href="https://www.facebook.com" class="bg-white p-2  mx-1  items-center justify-center rounded-full hover:bg-gray-300">
      <%= render '/shared/icons/facebook' %>
      </a>
      
      <!-- Discord Button -->
      <a href="https://www.discord.com" class="bg-white p-2  mx-1  items-center justify-center rounded-full hover:bg-gray-300">
      <%= render '/shared/icons/discord', width:20 %>
      </a>

      </div>
    </div>

    <!-- Corporate Logo Block -->
    <div class="flex-1 p-2">
      <%= link_to root_path do %>
        <%= image_tag 'BarCitizenLogo.png', alt: 'Bar Citizen Logo', class: 'logo-class' %>
    <% end %>
    </div>
  </div>

  <div class="text-center p-4">
    <p>&copy; BarCitizen 2954</p>
  </div>
</footer>

app/views/shared/_main_menu.html.erb
<style>
#main_menu .orb-font{
letter-spacing:3px;
}
.car-citizen-logo{
  width:90px !important;
}
</style>

<div class="bg-citizen-blue-base drop-shadow-lg flex items-center p-2 text-white relative rounded-lg m-2" style="z-index:9001; min-height: 55px;">
  <div class="flex-grow">
    <%= link_to root_path do %>
      <%= image_tag 'bar_citizen_white_black.png', alt: 'Bar Citizen Logo', class: 'logo-class bar-citizen-logo absolute h-auto' %>
    <% end %>
  </div>
  <!-- Hamburger Button for Mobile -->
  <div class="md:hidden flex items-center">
    <button id="mobile-menu-button" class="text-white focus:outline-none focus:shadow-outline" onclick="document.getElementById('mobile-menu').classList.toggle('hidden');">
      <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
    </button>
  </div>
  
  <!-- Mobile Menu -->
  <div id="mobile-menu" class="hidden md:hidden">
    <nav class="flex flex-col items-center space-y-2 mt-2">
      <% if current_user && current_user.user_type < 69 %>
      <%= link_to t('menu.dashboard'), dashboard_path, class: "text-white orb-font" %>
      <% else %>
      <%= link_to t('menu.home'), root_path, class: "text-white orb-font" %>
      <% end %>
  
      <%= link_to t('menu.event_map'), map_path, class: "text-white orb-font" %>
      <%= link_to t('menu.event_list'), events_path, class: "text-white orb-font" %>
      <%= link_to t('menu.gallery'), root_path, class: "text-white orb-font" %>
      <%= link_to t('menu.learn_more'), page_path('learn-more'), class: "text-white orb-font" %>
      <%= link_to t('menu.coordinators'), page_path('coordinators'), class: "text-white orb-font" %>
    </nav>
  </div>
  
  <!-- Main Menu for Desktop -->
  <nav id="main_menu" class="hidden md:flex flex-grow justify-between space-x-4">

<div class="relative">

<%= link_to t('menu.event_map'), map_path, class: "relative orb-font drop-shadow-xl" %>
</div>
<div class="relative">

<%= link_to t('menu.event_list'), events_path, class: "relative orb-font drop-shadow-xl" %>
</div>
<div class="relative">

<%= link_to t('menu.gallery'), gallery_path, class: "relative orb-font drop-shadow-xl" %>
</div>

<div class="relative">
  <%= link_to t('menu.learn_more'), page_path('learn-more'), class: "relative orb-font drop-shadow-xl" %>
  </div>
  <div class="relative">
  <%= link_to t('menu.coordinators'), page_path('coordinators'), class: "relative orb-font drop-shadow-xl" %>
  </div>
</nav>

  
  <div class="hidden md:flex-grow md:flex justify-end">
    <input type="search" placeholder="Search Discords" class="p-2 bg-gray-700 text-white">
  </div>
</div>


<style>
#main_menu .drop-shadow-xl{
text-shadow: 1px 2px 2px black;
}
#main_menu img{
max-width: inherit;
transform: translateX(-50%);
left: 50%;
    }
    .bmm{width: 120px; top: -17px;}
    .carrack{width: 160px; top: -15px;}
    .starfarer{width: 140px; top: -7px;}
    .hullc{width: 140px; top: -17px;}
    .origin{width: 160px; top: -5px;}
</style>

app/views/shared/_top_bar.html.erb
<div class="top-header bg-citizen-blue-dk  py-2 px-4 flex justify-between mx-2 mt-2 items-center space-x-4 text-gray-200 rounded-full">
<div class="text-gray-200"></div>
  <!-- Social Links Here -->
  <div class="social-links flex">
    <!-- Instagram Button -->
    <a href="https://www.instagram.com" class="bg-white mx-1 items-center justify-center rounded-full hover:bg-gray-300">
   
        <%= render '/shared/icons/instagram' %>
    </a>
    
    <!-- Twitter Button -->
    <a href="https://www.twitter.com" class="bg-white mx-1  items-center justify-center rounded-full hover:bg-gray-300">
    <%= render '/shared/icons/x' %>
    </a>
    
    <!-- Facebook Button -->
    <a href="https://www.facebook.com" class="bg-white  mx-1  items-center justify-center rounded-full hover:bg-gray-300">
    <%= render '/shared/icons/facebook' %>
    </a>
    
    <!-- Discord Button -->
    <a href="https://www.discord.com" class="bg-white  mx-1  items-center justify-center rounded-full hover:bg-gray-300">
    <%= render '/shared/icons/discord', width: 20 %>
    </a>
    <% comment do %>
    <select onchange="location = this.value;" class="bg-black">
      <option value="?locale=en" <%= 'selected' if I18n.locale == :en %>>English</option>
      <option value="?locale=fr" <%= 'selected' if I18n.locale == :fr %>>Francais</option>
      <option value="?locale=ja" <%= 'selected' if I18n.locale == :ja %>>日本語</option>
    </select>

    <% end %>

    <!-- Language Selector Wrapper -->
<div id="languageSelector" class="relative rounded-full bg-gray-900 ">
  <!-- Selected Language Display -->
  <div class="cursor-pointer overflow-hidden rounded-full mx-1  w-7 h-7" id="selectedLanguage">
    <% case I18n.locale %>
    <% when :en %>
      <%= raw File.read(Rails.root.join('app', 'assets', 'svg', 'england.svg')) %>
    <% when :fr %>
      <%= raw File.read(Rails.root.join('app', 'assets', 'svg', 'france.svg')) %>
    <% when :ja %>
      <%= raw File.read(Rails.root.join('app', 'assets', 'svg', 'japan.svg')) %>
    <% else %>
    <%= raw File.read(Rails.root.join('app', 'assets', 'svg', 'england.svg')) %>
    <% end %>
  </div



  <!-- Dropdown Menu -->
  <div id="languageDropdown" class="absolute rounded-br-full rounded-br-full bg-gray-900  hidden mt-1">
    <a href="?locale=en" class="block overflow-hidden rounded-full w-7 h-7">
    <%= raw File.read(Rails.root.join('app', 'assets', 'svg', 'england.svg')) %>
      <!-- Replace with actual SVG code -->
    </a>
    <a href="?locale=fr" class="block overflow-hidden rounded-full w-7 h-7">

    <%= raw File.read(Rails.root.join('app', 'assets', 'svg', 'france.svg')) %>
    </a>
    <a href="?locale=ja" class="block overflow-hidden rounded-full w-7 h-7">
    <%= raw File.read(Rails.root.join('app', 'assets', 'svg', 'japan.svg')) %>
    </a>
    <!-- Add more flags for other languages -->
  </div>


</div>


<% unless current_user %>
  <%= button_to  '/auth/discord', method: :post, class: 'discord-login-button bg-citizen-blue p-1 mx-4 rounded-r-full',  data: { turbo: false } do %>
    <%= render '/shared/icons/login' %>
  <% end %>
<% else %>
  <%= link_to dashboard_path do %>
    <img src="<%= current_user.profile_image %>" alt="User Profile" class="rounded-full mx-1  w-7 h-7">
  <% end %>
<% end %>

<!-- JavaScript for Dropdown Toggle -->
<script>
  document.getElementById('selectedLanguage').addEventListener('click', function() {
    document.getElementById('languageDropdown').classList.toggle('hidden');
  });

  window.addEventListener('click', function(e) {
    if (!document.getElementById('languageSelector').contains(e.target)) {
      document.getElementById('languageDropdown').classList.add('hidden');
    }
  });
</script>


  </div>

</div>