config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  # Define a route for standard pages
  get 'pages/:title', to: 'pages#show', as: :page

  # Define a route for nested pages
  get 'pages/:category/:title', to: 'pages#show_nested', as: :nested_page


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post '/api/exchange_token', to: 'authentication#exchange_token'

  get '/api/redirect_to_discord', to: 'authentication#redirect_to_discord'
  get '/api/discord/callback', to: 'authentication#discord_callback'
  get '/api/discord/start_auth', to: 'authentication#start_auth'

  get '/map', to: 'maps#index'

  resources :regions
  resources :wall_comments, only: [:create, :destroy]
  resources :discords
  resources :photos do
    resources :photo_comments do 
      post 'upvote'
      post 'downvote'
    end
    member do
      post 'view'
      post 'upvote'
      post 'downvote'
    end
  end
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  resources :votes, only: [:create]
  get '/dashboard', to: 'home#dashboard'
  get '/gallery', to: 'home#gallery'
  resources :messages
  # Events
 # get '/events/new', to: 'events#new', as: 'new_event'
 # get '/events', to: 'events#index', as: 'find_event'
 # post '/events', to: 'events#create'

 #post '/admin/events/:id/publish', to: 'admin#publish_event', as: 'publish_event'
 #post '/admin/events/:id/trash', to: 'admin#trash_event', as: 'trash_event'

 namespace :api do
  resources :regions, only: [:index], defaults: { format: :json }
  resources :events, only: [:index], defaults: { format: :json }
  # other API routes...
end

  namespace :admin do
    root to: 'dashboard#index'  # Example admin dashboard
    get '/calendar', to: 'calendar#index'
    get '/profile', to: 'users#show'
    resources :events do
      collection do
        get 'all', to: 'events#all'  # Adding this line
      end
      member do
        post 'publish'
        post 'trash'
      end
    end

    resources :regions do
      member do
        post 'publish'
        post 'trash'
      end
    end
    resources :sections, only: [:create, :destroy, :update]
    resources :blocks, only: [:create, :destroy, :update]
    resources :settings 
    resources :pages
    resources :posts do
      member do
        post 'trash'
      end
    end

    resources :replies do
      member do
        post 'trash'
      end
    end

    resources :messages do
      member do
        post 'trash'
      end
    end

    resources :badges do
      member do
        post 'trash'
      end
    end

    resources :user_badges do
      member do
        post 'trash'
      end
    end
    
    resources :discords do
      member do
        post 'publish'
        post 'unpublish'
        post 'trash'
      end
    end

    resources :users do
      member do
        post 'publish'
        post 'unpublish'
        post 'trash'
        patch :update_user_level, to: 'users#update_user_level'
      end
    end

    resources :photos do
      member do
        post 'publish'
        post 'unpublish'
        post 'trash'
      end
    end
  # ... other admin resources ...
  end

  resources :users, only: [:show, :edit, :update, :destroy]
  get 'new_category', to: 'post_categories#new'
  get 'virtual-events', to: 'events#virtual'
  get 'virtual-events/:slug', to: 'events#show_virtual', as: 'virtual_event'

  resources :events do
    resources :event_participations, only: [:create, :destroy]
    resources :photos, only: [:new, :create, :show, :destroy]
    resources :event_managers
    resources :giveaways do
      member do
        post 'draw_winner'
      end
    end
    member do
      post 'join'
      delete 'leave'
    end
  end

  get '/forum', to: 'forum#index'
  namespace :forum do
    get 'new_category', to: 'post_categories#new'
    resources :post_categories do
      resources :posts do
        resources :replies, only: [:new, :create, :show]
      end
    end
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'  
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/invite', to: 'events#invite', as: 'invite'


  # Defines the root path route ("/")
   root "home#index"
   get '/:id', to: 'regions#show', as: :region_shortcut
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @page = Page.find_by(title: 'homepage')

     @next_events = Event.where("start_datetime >= ?", Date.today)
    .order(:start_datetime)
    .limit(5)
    @newest_events = Event.where("start_datetime >= ?", Date.today).order(:created_at)
    @activities = Activity.all.order(:created_at).reverse_order
  end


  def gallery
    @photos = Photo.where(published:true)
  end
  
  def dashboard
    if !user_signed_in? || current_user.user_type == User::TRASH
      redirect_to root_path and return
    end
    BadgeAwardingService.new(current_user).call

    # Ensure that the user is authenticated before showing the dashboard
    current_user.update(last_login: DateTime.now)
    @username = current_user.username
    @activities = Activity.all.order(:created_at).reverse_order
    # Load more user data as needed
  end
end

app/views/home/_discord_management.html.erb
<% if current_user.user_level == "Regional Manager" %>
<!-- List of discord servers and details -->
<div class="citizen-grey-md text-white shadow-lg rounded-lg p-4 mb-4 md:col-span-2">
  <h2 class="text-xl text-white font-semibold mb-3">Managed Discord servers</h2>
  <% current_user.discords.each do |discord| %>
  <div class="flex flex-row w-full justify-between text-white">
    <div>
        <%= discord.server_name %>
    </div>
    <div>
    <%= link_to discord.discordable_type, discord.discordable %>

    </div>
    <div>
    <%= link_to discord.server_url %>
    </div>
    <div>
    <%= discord.created_at.strftime('%a %b %d, %Y %l:%M %p')%>
    </div>
    <div class="flex flex-row justify-between"> <%=link_to "Edit", edit_discord_path(discord) %> | <%= button_to "Delete", discord, method: :delete %> </div>
  </div>
  <hr class="m2" style="border-color: #8b8b8b">
  <% end %>
</div>
<% end %>

app/views/home/_four_block.html.erb
<section class="py-14">
<div class="grid grid-cols-1 md:grid-cols-2 gap-4 p-4">
  <div  class="group block bg-cover overflow-hidden bg-center w-full h-64 p-4 relative rounded-lg" style="background-image: url(<%= asset_url('featured_slides/bar_citizen_slide_1.jpg') %>); height: 72vh;" onclick="location.href='your-link-for-block-1';">
    <div class="absolute top-0 left-0 bg-black bg-opacity-50 text-white font-bold text-2xl p-2">What is Car Citizen?</div>
    <div class="overlay absolute inset-0 bg-black opacity-0 text-white group-hover:opacity-100 flex items-center justify-center p-4">
      <p>Car Citizen is a community-driven gathering for fans of Star Citizen and Squadron 42, offering a space to meet, share experiences, and celebrate their shared passion.</p>
    </div>
  </div>
    <div  class="group block bg-cover bg-center w-full h-64 p-4 relative rounded-lg overflow-hidden" style="background-image: url(<%= asset_url('featured_slides/bar_citizen_slide_2.jpg') %>); height: 72vh;" onclick="location.href='your-link-for-block-1';">
        <div class="absolute top-0 left-0 bg-black bg-opacity-50 text-white font-bold text-2xl p-2">Share your experience</div>
        <div class="overlay absolute inset-0 bg-black text-white opacity-0 group-hover:opacity-100 flex items-center justify-center p-4">
            <p>Explore themed game nights, cosplay contests, and space sim tutorials. Enjoy virtual meetups, trivia, and guest speaker sessions for immersive experiences</p>
        </div>
    </div>
<div  class="group block bg-cover bg-center w-full h-64 p-4 relative rounded-lg overflow-hidden" style="background-image: url(<%= asset_url('featured_slides/bar_citizen_slide_3.jpg') %>); height: 72vh;" onclick="location.href='your-link-for-block-1';">
<div class="absolute top-0 left-0 bg-black bg-opacity-50 text-white font-bold text-2xl p-2">Create New Event</div>
<div class="overlay absolute inset-0 bg-black text-white opacity-0 group-hover:opacity-100 flex items-center justify-center p-4">
  <p>Easily organize your own Car Citizen event! Choose a theme, set a date, and invite fellow enthusiasts. Perfect for local meetups or virtual gatherings</p>
</div>
</div>
<div class="group block bg-cover bg-center w-full h-64 p-4 relative rounded-lg overflow-hidden" style="background-image: url(<%= asset_url('featured_slides/bar_citizen_slide_4.jpg') %>); height: 72vh;" onclick="location.href='your-link-for-block-1';">
<div class="absolute top-0 left-0 bg-black bg-opacity-50 text-white font-bold text-2xl p-2">Discord List</div>
<div class="overlay absolute inset-0 bg-black text-white opacity-0 group-hover:opacity-100 flex items-center justify-center p-4">
  <p>Discover a vibrant gallery of Car Citizen moments! Browse through event snapshots, cosplay highlights, and memorable meetups, all shared by the community</p>
</div>
</div>
</div>
</section>
<style>
.overlay {
    cursor:pointer;
    transition: opacity 0.3s ease;
}
</style>

app/views/home/_hero.html.erb
<div style="height:90vh;"  class="hero mx-2 flex flex-col md:flex-row relative overflow-hidden p-1 rounded-lg">

  <!-- Left Block with Background Image -->
  <div class="w-full h-screen md:h-full md:w-4/6 bg-citizen-blue-highlight  p-1 text-left relative overflow-hidden	rounded-lg">
    <div class="w-full h-screen md:h-full background-div bg-cover bg-no-repeat bg-center overflow-hiddenp-4	rounded-lg"  style="background-image: url(<%= asset_url('featured_slides/bar_citizen_slide_1.jpg') %>);" >
      <!-- Content inside the image block for desktop -->
      <div class="hidden md:block md:absolute bottom-0 left-0 p-4">
        <h1 class="text-white text-4xl font-bold w-3/5">WORLD'S BIGGEST STAR CITIZEN EVENTS!</h1>
      </div>
      <div class="hidden md:block md:absolute bottom-0 right-0 p-4">
        <button class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">ATTEND EVENT</button>
        <p class="text-yellow-300 mb-4"><%= User.count %> MEMBERS AND GROWING!</p>
      </div>

      <!-- Content inside the image block for mobile -->
      <div class="md:hidden p-4 absolute bottom-0 w-full text-center">
        <h1 class="text-white text-4xl font-bold mb-4">WORLD'S BIGGEST STAR CITIZEN EVENTS!</h1>
        <button class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded w-full mb-4">ATTEND EVENT</button>
        <p class="text-yellow-300"><%= User.count %> MEMBERS AND GROWING!</p>
      </div>
    </div>
  </div>
  <!-- Right Block with Events List -->
  <div class="flex flex-col h-full bg-citizen-blue-highlight mt-2 md:mt-0 md:ml-2 md:w-2/6 w-full overflow-hidden text-white rounded-lg">
    <div class="flex flex-col  bg-citizen-blue-base items-center m-2 rounded-full">
      <h2 class="text-xl font-bold p-1"><%= t 'homepage.next_events' %>:</h2>
    </div>

  <!-- Outer div for padding and to act as a flex container -->
  <div class="flex-grow mt-1 p-1">
    <!-- Inner div for background and scrolling -->
    <div class="h-full bg-gray-800 rounded-lg overflow-auto">
      <% @next_events.each_with_index do |event, index| %>
        <%= link_to event, class: "#{index.even? ? 'citizen-grey-md' : 'citizen-grey-dk'} p-2 flex items-center justify-between flex-row" do %>
          <span class="font-light text-xs"><%= event.title %></span>
          <span class="font-light text-xs"><%= event.start_datetime.in_time_zone(event.timezone).strftime("%b %e, %Y %l%p") %> <%= timezone_abbreviation(event.timezone) %> </span>
          
        <% end %>
      <% end %>
      <%= link_to t('homepage.see_all_events'), events_path, class: 'mx-auto flex mt-2 justify-center w-1/2' %>
      
    </div>
  </div>
</div>



</div>
  <style>
  @media (max-width: 767px) {
.hero{
  height:auto !important;
}
.background-div{
  height:90vh !important;
}
.hero .h-screen{
  height:90vh !important;
}
      }
</style>

app/views/home/_newsfeed.html.erb
<section class="py-14 newsfeed"> <!-- Changed to darker background for dark theme -->
  <div class="grid grid-cols-1 md:grid-cols-2 gap-16 py-8 px-14 text-white">
    
    <!-- New Events Block -->
    <div class="bg-gray-800 border border-gray-700 rounded-lg"  style="height:32rem;"> <!-- Rounded corners added -->
      <div class="px-4 py-4 bg-citizen-blue-base rounded-t-lg"> <!-- Dark header with rounded top -->
        <h3 class="text-2xl font-bold text-center"><%= t 'homepage.newsfeed.new_events' %></h3>
      </div>
      <hr class="border-gray-700"> <!-- Horizontal rule -->
      <div class="px-4 py-4">
        <!-- Repeat for each event -->
        <% @newest_events.each do |event| %>
        <div class="flex py-4">
          <% banner_url = url_for(event.banner) if event.banner.attached? %>
          <img src="<%= banner_url %>" alt="Event Thumbnail" class="rounded-lg h-12">
          <div class="ml-4">
            <p><%= link_to event.title, event, class:'font-semibold' %> • <%= link_to event.region.name, event.region, class:'citizen-blue-highlight underline underline-offset-4' %></p>
            <span class="text-sm">Starts <%=  event.start_datetime.in_time_zone(event.timezone).strftime("%b %e, %Y %l%p") %></span>
            

          </div>
        </div>
        <hr class="border-gray-700"> <!-- Horizontal rule -->

        <% end %>
        <!-- ... additional events ... -->
      </div>
    </div>

    <!-- New Activities Block -->

    <div class="bg-gray-800 border border-gray-700 rounded-lg" style="height:32rem;">
      <div class="px-4 py-4 bg-citizen-blue-base rounded-t-lg">
        <h3 class="text-2xl font-bold text-center"><%= t 'homepage.newsfeed.new_activities' %></h3>
      </div>
      <hr class="border-gray-700">
      <!-- Set a max-height to accommodate the header and horizontal rule. Adjust the value as needed. -->
      <div class="overflow-auto" style="max-height: calc(32rem - 4rem); box-sizing: border-box;">
        <div class="px-4 py-4">
          <!-- Repeat for each activity -->

              
              <% @activities.each do |activity| %>
                <div class="flex py-4">
                  <img src="<%= activity.user.profile_image %>" alt="User Profile" class="rounded-full h-12">
                  <div class="ml-4">
                    <p class="font-semibold">
                      <%= activity.user.username %>
                      <% case activity.name %>
                      <% when "New discord created" %>
                        created a new Discord
                      <% when "User joined" %>
                      <%=  t 'homepage.newsfeed.attending' %> <%= link_to activity.user_event.title, event_path(activity.user_event), class:'underline' %> event
                      <% when "User signup" %>
                        created a new account

                      <% when "Giveaway won" %>
                        won a <%= activity.giveaway_won.title %> from the <%= link_to activity.giveaway_won.event.title, event_path(activity.giveaway_won.event), class:'underline' %>
                      <% when "New reply created" %>
                        posted a reply
                      <% when "New EventManager created" %>
                        Assigned a new manager to the event
                      <% when "New photo created" %>
                      <% event_id = activity.photo&.event&.id %>
                        <% if event_id %>
                        <%=  t 'homepage.newsfeed.new_photo' %> <%= link_to activity.photo.event.title, event_path(activity.photo.event), class:'underline' %>
                        <% end %>
                      <% when "New region created" %>
                        created a new region
                      <% when "Bug submitted" %>
                        submitted a bug
                      <% when "Created event" %>
               
                        <%=  t 'homepage.newsfeed.new_event' %> <% if activity.event %> <%= link_to activity.event.title, event_path(activity.event), class:'underline' %> <% else %> deleted <% end %>
                      <% when "New post created" %>
                          <%=  t 'homepage.newsfeed.new_post' %><%= link_to activity.post.post_category.name, forum_post_category_post_path(activity.post.post_category, activity.post), class:'underline' %> 
                      <% when "New giveaway added" %>
                      <% event_id = activity.giveaway&.event_id %>
                        <% if event_id %>
                        <%= t 'homepage.newsfeed.new_giveaway' %>
                        <%= link_to activity.giveaway.event.title, event_path(activity.giveaway.event), class:'underline' %>
                        <% else %>
                        Deleted giveaway
                        <% end %>
                      <% else %>
                        <%= activity.name %>
                      <% end %>
                    </p>

                    <p class="text-xs"><%= time_ago_in_words(activity.created_at) %> ago</p>
                    <!-- Additional Activity Details Here -->
                  </div>
                </div>
                <hr class="border-gray-700"> <!-- Horizontal rule -->
              <% end %>
              


        </div>
      </div>
    </div>
    

  </div>
</section>

<style>
@media (min-width: 767px) {
section.newsfeed{
  height: 90vh;
}
              }
</style>

app/views/home/_newsletter.html.erb
<section class="py-14">
<div class="bg-blue-600 p-4 text-center flex flex-col justify-center items-center h-screen" style="height: 50vh;">
  <h3 class="text-4xl text-white mb-6"><%= t 'homepage.newsletter' %></h3>
  <div class="w-full flex flex-col md:flex-row md:space-x-4 justify-center items-center">
    <input type="text" placeholder="Enter your username" class="placeholder-gray-700 bg-gray-800 text-white text-xl py-3 px-4 rounded-full w-full mb-4 md:mb-0 md:w-1/4">
    <input type="email" placeholder="Enter your email address" class="placeholder-gray-700 bg-gray-800 text-white text-xl py-3 px-4 rounded-full w-full mb-4 md:mb-0 md:w-1/4">
    <button class="bg-citizen-blue-highlight text-white py-3 px-6 rounded-full text-xl w-full md:w-auto">Submit</button>
  </div>
</div>
</section>

app/views/home/_three_block_cta.html.erb
<section class="py-14">
<div class="grid grid-cols-1 md:grid-cols-3 gap-4 p-4" style="height:70vh;">
  <!-- Block 1 -->
  <div class="relative bg-cover bg-center p-6 flex justify-center items-center flex-col cursor-pointer" style="background-image: url(<%= asset_url('featured_slides/bar_citizen_slide_4.jpg') %>);" onclick="location.href='your-link-for-block-1';">
    <h3 class="text-white text-xl font-bold mb-2">Block Title 1</h3>
    <p class="text-white mb-4">Block Subtext 1</p>
    <div class="border border-white py-2 px-4 text-white cursor-pointer">Block CTA 1</div>
  </div>

  <div class="relative bg-cover bg-center p-6 flex justify-center items-center flex-col cursor-pointer" style="background-image: url(<%= asset_url('featured_slides/bar_citizen_slide_2.jpg') %>);" onclick="location.href='your-link-for-block-1';">
  <h3 class="text-white text-xl font-bold mb-2">Block Title 1</h3>
  <p class="text-white mb-4">Block Subtext 1</p>
  <div class="border border-white py-2 px-4 text-white cursor-pointer">Block CTA 1</div>
</div>

<div class="relative bg-cover bg-center p-6 flex justify-center items-center flex-col cursor-pointer" style="background-image: url(<%= asset_url('featured_slides/bar_citizen_slide_3.jpg') %>);" onclick="location.href='your-link-for-block-1';">
<h3 class="text-white text-xl font-bold mb-2">Block Title 1</h3>
<p class="text-white mb-4">Block Subtext 1</p>
<div class="border border-white py-2 px-4 text-white cursor-pointer">Block CTA 1</div>
</div>
  
  
  <!-- Repeat for other two blocks -->
</div>
</section>

app/views/home/_video.html.erb
<section class="py-14">
<div class="flex flex-col md:flex-row items-center p-4 text-white">
  <!-- Text Area -->
  <div class="w-full md:w-1/2 p-4">
    <h5 class="text-2xl font-bold">Connect with Fellow Space Enthusiasts</h5>  
    <p>
      Whether you're a seasoned explorer of the stars or just starting your journey in the universe, Car Citizen gatherings are designed to bring space enthusiasts together in a fun and relaxed setting.
    </p>
    <p>
      Join us for six weeks of interstellar socializing, where you can team up with fellow citizens, engage in themed trivia for exclusive prizes, and then drift over to the post-event gathering spot. Here, you'll have the chance to enjoy space-themed bar and board games and mingle with the wider community!
    </p>
    <p>
      Why orbit the same old routines when you can launch into new adventures? Assemble your crew, sign up solo, or form a squadron with your colleagues for an unforgettable space-themed experience. Check out the video for more details on how to join the galactic fun! 🚀🌌
    </p>
  </div>

  <!-- Video Area -->
  <div class="w-full md:w-1/2 relative" style="min-height: 390px;">
    <iframe class="absolute top-0 left-0 w-full h-full rounded-lg overflow-hidden" src="https://www.youtube.com/embed/GIojzZ_kIbE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen style="object-fit: cover;"></iframe>
  </div>
</div>
</section>

app/views/home/dashboard.html.erb
<!-- app/views/home/dashboard.html.erb -->
<div class="container mx-auto px-4 py-8">
  <h1 class="text-2xl font-bold mb-4">User Dashboard</h1>
  
  <% if @username %>
    <div class="citizen-grey-md text-white shadow-lg rounded-lg p-4 mb-4">
      <p class="text-lg">Welcome, <%= @username %>! You have successfully logged in with Discord.</p>
      <!-- Display more user information if available -->
    </div>

    <div class="flex bg-citizen-blue-dk rounded-lg flex-wrap gap-4 mb-4">

    <%= link_to 'My profile', user_path(@current_user), class: 'btn hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>

    <% if current_user.user_level == "Regional Manager" || current_user.user_type < 1 %>
    <%= link_to 'Create Discord', new_discord_path, class: 'btn hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
    <% if current_user.region %>
    <%= link_to 'Region Page', region_path(current_user.region), class: 'btn text-white font-bold py-2 px-4 rounded' %>
    <% end %>
    <% end %>

      <%= link_to 'Create Event', new_event_path, class: 'btn text-white font-bold py-2 px-4 rounded' %>
      <%= link_to 'Find Event', events_path, class: 'btn text-white font-bold py-2 px-4 rounded' %>
      <%= link_to 'Message Board', forum_path, class: 'btn text-white font-bold py-2 px-4 rounded' %>
      <% if current_user&.user_type <= 1 %>
      <%= link_to 'Admin Dashboard', admin_root_path,  class: 'btn bg-purple-500 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded'  %>
    <% end %>
      <%= button_to 'Logout', logout_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded' %>

      </div>

    <!-- Additional Dashboard Sections -->

<%= render 'discord_management' %>

    <div class="grid md:grid-cols-2 gap-4">
      <!-- Upcoming Events Section -->
      <div class="citizen-grey-dk shadow-lg rounded-lg p-4">
        <h2 class="text-xl text-white font-semibold mb-3">Upcoming Events</h2>
        <!-- List of upcoming events -->
      </div>

      <!-- Event Recommendations Section -->
      <div class="citizen-grey-md shadow-lg rounded-lg p-4" style="max-height:300px;">
        <h2 class="text-xl text-white font-semibold mb-3">Recent Activity</h2>
        <ul style="height: 13rem; overflow-y:scroll;">
        <%  @activities.each do |activity|   %>
          <li class="text-white">
            <%= activity.name %> by <%= activity.user.username %> at <%= activity.created_at.strftime("%a, %b %d, %Y %l:%M %p") %>
          </li>
        <% end %>
        </ul>
      </div>

      <!-- User Participation Statistics -->
      <div class="citizen-grey-md text-white shadow-lg rounded-lg p-4 md:col-span-2">
        <h2 class="text-xl text-white font-semibold mb-3">Your Participation</h2>
        <!-- Statistics and graphs about the user's event participation -->
      </div>
    </div>
  <% else %>
    <p class="text-lg">You are not logged in.</p>
  <% end %>
</div>

app/views/home/gallery.html.erb

<div id="photos" class="p-5 sm:p-8">
  <div class="columns-1 gap-5 sm:columns-2 sm:gap-8 md:columns-3 lg:columns-3 [&>div:not(:first-child)]:mt-8">
    <% @photos.each do |photo| %>
        <%= link_to photo, class: "" do %> 
            <div class="break-inside-avoid bg-white shadow-lg rounded-lg overflow-hidden">
                <% if photo.image.attached? %>
                    <%= image_tag photo.image, alt: "Photo", class: "w-full" %>        
                    <!-- Photo Title -->
                    <div class="px-4 py-2 bg-gray-800">
                    <h3 class="text-white text-lg font-semibold"><%= photo.title %></h3>
                    </div>

                    <!-- Interaction Row -->
                    <div class="px-4 py-2 bg-gray-800 flex justify-between items-center">
                    <span class="text-gray-100">👍 <%= photo.votes.where(upvote: true).count  %></span>
                    <span class="text-gray-100">💬 <%= photo.photo_comments.count %></span>
                    <span class="text-gray-100">👀 <%= photo.views %> </span>
                    </div>

                <% end %>
            </div>
        <% end %>
        <% end %>
  </div>
</div>



<style>
.break-inside-avoid {
  break-inside: avoid;
  margin-bottom: 1rem;
}

</style>

app/views/home/index.html.erb




<% @page&.sections&.order(:section_order)&.each do |section| %>
  <% section_type = section.sectionable_type.downcase.gsub('section', '') %>
  <%= render partial: "/section/#{section_type}_section", locals: { section: section.sectionable } %>

  <hr class="bg-citizen-blue-base my-5 mx-4 citizen-blue rounded-full h-8 border-0">
<% end %>

<%= render 'newsfeed' %>



<%= render 'newsletter' %>
<!-- Add your own styling for the login button -->
<style>
  .discord-login-button {
    /* Style your button here */
    background-color: #7289DA; /* Discord's brand color */
    color: white;
    padding: 4px;
    border: none;
    border-radius: 5px;
    text-decoration: none;
    font-size: 16px;
  }
</style>