config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  # Define a route for standard pages
  get 'pages/:title', to: 'pages#show', as: :page

  # Define a route for nested pages
  get 'pages/:category/:title', to: 'pages#show_nested', as: :nested_page


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post '/api/exchange_token', to: 'authentication#exchange_token'

  get '/api/redirect_to_discord', to: 'authentication#redirect_to_discord'
  get '/api/discord/callback', to: 'authentication#discord_callback'
  get '/api/discord/start_auth', to: 'authentication#start_auth'

  get '/map', to: 'maps#index'

  resources :regions
  resources :wall_comments, only: [:create, :destroy]
  resources :discords
  resources :photos do
    resources :photo_comments do 
      post 'upvote'
      post 'downvote'
    end
    member do
      post 'view'
      post 'upvote'
      post 'downvote'
    end
  end
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  resources :votes, only: [:create]
  get '/dashboard', to: 'home#dashboard'
  get '/gallery', to: 'home#gallery'
  resources :messages
  # Events
 # get '/events/new', to: 'events#new', as: 'new_event'
 # get '/events', to: 'events#index', as: 'find_event'
 # post '/events', to: 'events#create'

 #post '/admin/events/:id/publish', to: 'admin#publish_event', as: 'publish_event'
 #post '/admin/events/:id/trash', to: 'admin#trash_event', as: 'trash_event'

 namespace :api do
  resources :regions, only: [:index], defaults: { format: :json }
  resources :events, only: [:index], defaults: { format: :json }
  # other API routes...
end

  namespace :admin do
    root to: 'dashboard#index'  # Example admin dashboard
    get '/calendar', to: 'calendar#index'
    get '/profile', to: 'users#show'
    resources :events do
      collection do
        get 'all', to: 'events#all'  # Adding this line
      end
      member do
        post 'publish'
        post 'trash'
      end
    end

    resources :regions do
      member do
        post 'publish'
        post 'trash'
      end
    end
    resources :sections, only: [:create, :destroy, :update]
    resources :blocks, only: [:create, :destroy, :update]
    resources :settings 
    resources :pages
    resources :posts do
      member do
        post 'trash'
      end
    end

    resources :replies do
      member do
        post 'trash'
      end
    end

    resources :messages do
      member do
        post 'trash'
      end
    end

    resources :badges do
      member do
        post 'trash'
      end
    end

    resources :user_badges do
      member do
        post 'trash'
      end
    end
    
    resources :discords do
      member do
        post 'publish'
        post 'unpublish'
        post 'trash'
      end
    end

    resources :users do
      member do
        post 'publish'
        post 'unpublish'
        post 'trash'
        patch :update_user_level, to: 'users#update_user_level'
      end
    end

    resources :photos do
      member do
        post 'publish'
        post 'unpublish'
        post 'trash'
      end
    end
  # ... other admin resources ...
  end

  resources :users, only: [:show, :edit, :update, :destroy]
  get 'new_category', to: 'post_categories#new'
  get 'virtual-events', to: 'events#virtual'
  get 'virtual-events/:slug', to: 'events#show_virtual', as: 'virtual_event'

  resources :events do
    resources :event_participations, only: [:create, :destroy]
    resources :photos, only: [:new, :create, :show, :destroy]
    resources :event_managers
    resources :giveaways do
      member do
        post 'draw_winner'
      end
    end
    member do
      post 'join'
      delete 'leave'
    end
  end

  get '/forum', to: 'forum#index'
  namespace :forum do
    get 'new_category', to: 'post_categories#new'
    resources :post_categories do
      resources :posts do
        resources :replies, only: [:new, :create, :show]
      end
    end
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'  
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/invite', to: 'events#invite', as: 'invite'


  # Defines the root path route ("/")
   root "home#index"
   get '/:id', to: 'regions#show', as: :region_shortcut
end

app/controllers/admin/settings_controller.rb
# app/controllers/admin/dashboard_controller.rb

module Admin
    class SettingsController < ApplicationController
      before_action :authenticate_admin!
      layout 'admin'

      def edit
        @section = Section.find(params[:id])
        @section.blocks.each do |block|
          ['en', 'ja'].each do |lang|
            block.translations.find_or_initialize_by(language: lang)
          end
        end
      end

      def index
        # Dashboard summary data
        @section = Section.new
        @sections = Section.all
      end
    end
  end
  

app/views/admin/settings/_form_blocks.html.erb
<div class="container mx-auto px-4 dark:bg-gray-800">
  <h1 class="text-xl font-bold my-4 text-gray-900 dark:text-white">New Block</h1>
  <%= form_with model: Block.new, url: admin_blocks_path, local: true, class: "flex flex-row flex-wrap gap-4" do |form| %>
    
    <div class="flex-1 mb-4">
      <%= form.label :title, class: 'text-gray-900 dark:text-white' %>
      <%= form.text_field :title, class: "shadow border rounded py-2 px-3 text-gray-700 dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700" %>
    </div>

    <div class="flex-1 mb-4">
    <%= form.label :image, 'Image URL', class: 'text-gray-900 dark:text-white' %>

        <%= form.file_field :image, class:'shadow border rounded py-2 px-3 text-gray-700 dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700' %>

    </div>

    <div class="flex-1 mb-4">
      <%= form.label :link_url, 'Link URL', class: 'text-gray-900 dark:text-white' %>
      <%= form.text_field :link_url, class: "shadow border rounded py-2 px-3 text-gray-700 dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700" %>
    </div>

    <div class="flex-1 mb-4">
      <%= form.label :section_id, 'Section', class: 'text-gray-900 dark:text-white' %>
      <%= form.collection_select :section_id, Section.all, :id, :sectionable_title, { prompt: 'Select a Section' }, { class: "shadow border rounded py-2 px-3 dark:border-gray-600 dark:bg-gray-700" } %>
    </div>

    <div class="mb-4">
      <%= form.submit "Create Block", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
    </div>
  <% end %>
</div>

app/views/admin/settings/_form_section.html.erb
<div class="container mx-auto px-4 dark:bg-gray-800">
  <h1 class="text-xl font-bold my-4 text-gray-900 dark:text-white">New Section</h1>
  <%= form_with model: Section.new, url: admin_sections_path, local: true, class: "flex flex-row flex-wrap gap-4" do |form| %>
    
    <div class="flex-1 mb-4">
      <%= form.label :title, class: 'text-gray-900 dark:text-white' %>
      <%= form.text_field :title, class: "shadow border rounded py-2 px-3 text-gray-700 dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700" %>
    </div>

    <div class="flex-1 mb-4">
      <%= form.label :section_order, class: 'text-gray-900 dark:text-white' %>
      <%= form.number_field :section_order, class: "shadow border rounded py-2 px-3 dark:border-gray-600 dark:bg-gray-700" %>
    </div>

    <div class="flex-1 mb-4">
      <%= form.label :section_type, 'Section Type', class: 'text-gray-900 dark:text-white' %>
      <%= form.select :section_type, options_for_select(['VideoSection', 'HeroSection', 'TwoByTwoGridSection', 'ThreeGridSection', 'ContentSection', 'ImageText']), {}, { class: 'shadow border rounded py-2 px-3 dark:border-gray-600 dark:bg-gray-700', id: 'section_type_select' } %>
    </div>

    <div class="flex-1 mb-4">
      <%= form.label :page_id, 'Page', class: 'text-gray-900 dark:text-white' %>
      <%= form.collection_select :page_id, Page.all, :id, :title, { prompt: 'Select a Page' }, { class: "shadow border rounded py-2 px-3 dark:border-gray-600 dark:bg-gray-700" } %>
    </div>

    <div class="mb-4">
      <%= form.submit "Save", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
    </div>
  <% end %>
</div>

app/views/admin/settings/_section.html.erb

<div class="grid grid-cols-3 border-b border-stroke dark:border-strokedark sm:grid-cols-6">
<div class="flex items-center gap-3 p-2.5 xl:p-5">
  <div class="flex-shrink-1">
    <img src="<%= section.page.user.profile_image %>" alt="User" />
  </div>
  <p class="hidden font-medium  dark:text-white sm:block">
    <%= section.page.user.username %>
  </p>
</div>

<div class="flex items-center justify-center p-2.5 xl:p-5" style="max-width:100px; overflow-x:scroll">
  <p class="font-medium  dark:text-white"><%= section.page.title %></p>
</div>
<div class="flex items-center justify-center p-2.5 xl:p-5">
  <p class="font-medium  dark:text-white"><%= section.sectionable.title %></p>
</div>

<div class="hidden items-center justify-center p-2.5 sm:flex xl:p-5">
  <p class="font-medium text-meta-5 text-white"> <%= section.sectionable_type %></p>
</div>

<div class="hidden items-center justify-center p-2.5 sm:flex xl:p-5">
  <p class="font-medium dark:text-white"><%= section.sectionable.created_at.strftime('%a %b %d, %Y %l:%M %p') %></p>
</div>

<div class="hidden items-center justify-center p-2.5 sm:flex xl:p-5">
<p class="font-medium text-meta-5 text-white">
<%= link_to 'Edit', edit_admin_setting_path(section), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>

Trash
</p>
</div>

<!-- Displaying Blocks within the Section -->
<div class="col-span-3 sm:col-span-6">
  <% section.blocks.each do |block| %>
    <div class="flex items-center justify-between p-2">
      <!-- Adjust the styling as needed -->
      <p class="text-xs dark:text-white truncate">Title: <%= block.title %></p>
      <p class="text-xs dark:text-white truncate">Image URL: <%= block.image %></p>
      <p class="text-xs dark:text-white truncate">Link URL: <%= block.link_url %></p>

      <!-- Additional block details here -->
    </div>
  <% end %>
</div>


</div>

app/views/admin/settings/edit.html.erb
<div class="container mx-auto px-4 dark:bg-gray-800">
  <h1 class="text-xl font-bold my-4 text-gray-900 dark:text-white">Edit Section</h1>
  
  <!-- Form for editing the sectionable attributes -->
  <% comment do %>
  <%= form_with model: @section, url: admin_section_path(@section), local: true do |form| %>

    <!-- Add fields specific to the sectionable type -->
    <!-- Example for a VideoSection -->
    <% if @section.sectionable_type == "VideoSection" %>
      <%= form.label :title %>
      <%= form.text_field :title %>
      <!-- Other fields specific to VideoSection -->
    <% end %>
    <!-- Add similar conditional blocks for other sectionable types -->

    <%= form.submit 'Update Section', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
  <% end %>
  <% end %>
  <%= button_to 'Delete Section', admin_section_path(@section), method: :delete, data: { confirm: 'Are you sure?' }, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>

  <!-- Forms for editing blocks -->
  <% @section.blocks.each do |block| %>
    <%= form_with model: [:admin, block], local: true do |form| %>
      <%= form.label :title %>
      <%= form.text_field :title %>

      <%= form.label :description %>
      <%= form.text_area :description %>


      <%= form.label :link_url %>
      <%= form.text_field :link_url %>
      
      <div>
      <%= form.label :image %>
      <%= form.file_field :image, class:'w-full bg-gray-700 text-white' %>
</div>

      <h2 class="text-lg font-bold mt-4 mb-2">Translations</h2>
      <%= form.fields_for :translations, block.translations do |translation_form| %>
        <div class="border p-4 rounded mb-2">
          <%= translation_form.label :language %>
          <%= translation_form.text_field :language %>
      
          <%= translation_form.label :title %>
          <%= translation_form.text_field :title %>
      
          <%= translation_form.label :description %>
          <%= translation_form.text_area :description %>
        </div>
      <% end %>

      <%= form.submit 'Update Block', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
    <% end %>
    <%= button_to 'Delete Block', admin_block_path(block), method: :delete, data: { confirm: 'Are you sure?' }, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>

  <% end %>

  <!-- Back Button -->
  <%= link_to 'Back to Settings', admin_settings_path, class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded" %>
</div>

app/views/admin/settings/index.html.erb

<!-- ===== Main Content Start ===== -->
<main class="w-full">
  <div class="mx-auto max-w-screen-2xl p-4 md:p-6 2xl:p-10">


    
    <div class="container mx-auto px-4">
    <h1 class="text-xl font-bold my-4">Settings Dashboard</h1>

<%= render 'form_section' %>
<%= render 'form_blocks' %>

<div class="rounded-sm border border-gray-300 shadow-md dark:border-gray-700 dark:bg-gray-800">


  <div class="grid grid-cols-3 rounded-sm bg-gray-900 dark:bg-gray-900 sm:grid-cols-6">
    <div class="p-2.5 xl:p-5">
      <h5 class="text-sm font-medium uppercase xsm:text-base text-gray-900 dark:text-white">Author</h5>
    </div>
    <div class="p-2.5 text-center xl:p-5">
      <h5 class="text-sm font-medium uppercase xsm:text-base text-gray-900 dark:text-white">Page</h5>
    </div>
    <div class="p-2.5 text-center xl:p-5">
      <h5 class="text-sm font-medium uppercase xsm:text-base text-gray-900 dark:text-white">Post</h5>
    </div>
    <div class="p-2.5 text-center xl:p-5">
      <h5 class="text-sm font-medium uppercase xsm:text-base text-gray-900 dark:text-white">TYpe</h5>
    </div>
    <div class="hidden p-2.5 text-center sm:block xl:p-5">
      <h5 class="text-sm font-medium uppercase xsm:text-base text-gray-900 dark:text-white">Created</h5>
    </div>
    <div class="hidden p-2.5 text-center sm:block xl:p-5">
    <h5 class="text-sm font-medium uppercase xsm:text-base text-gray-900 dark:text-white">Action</h5>
  </div>
  </div>

  <% if @sections.count > 0 %>
    <% @sections.each do |section| %>
      <%= render 'section', section: section %>
    <% end %>
  <% else %>
    <div class="text-center py-4">
      <p class="text-gray-500 dark:text-gray-400">No sections found.</p>
    </div>
  <% end %>

</div>




  </div>
</main>